### ISSUE TITLE
Add PNotify.

### ISSUE THREAD

**Issue by hperrin** [flagello/awesome-sveltejs#9]
PNotify 4 is built with Svelte.

https://sciactive.github.io/pnotify/

I'm not sure where it would fit in though. You don't normally use it like a regular Svelte component, so it doesn't really fit in with the other components. Maybe it could go in examples. It's a big project, written almost all in Svelte.

**Comment by flagello** [comment]
Thanks for the heads up! I’ve added a new _Built with Svelte_ section.
